# Generated by Django 4.1 on 2022-09-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_description_items_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name_plural': 'Description'},
        ),
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(default='item', max_length=200),
        ),
    ]
